/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appempresaseguridad.gui.secretaria;

import appempresaseguridad.data.entity.Persona;
import appempresaseguridad.data.entity.Rol;
import appempresaseguridad.data.entity.TipoDocumento;
import appempresaseguridad.data.entity.Usuario;
import appempresaseguridad.logic.secretaria.SecretariaLogica;
import appempresaseguridad.util.StringUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author alejrudu
 */
public class CreacionEmpleadoDialog extends javax.swing.JDialog {

    private final SecretariaLogica logica;

    /**
     * Creates new form CreacionEmpleadoFrame
     */
    public CreacionEmpleadoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.logica = new SecretariaLogica();
        cbTiposDocumento.addItem("< ---- >");
        cbRol.addItem("< ---- >");
        this.logica.getListaTiposDocumento().forEach(
                item -> cbTiposDocumento.addItem(item)
        );
        this.logica.getListaRoles().forEach(
                item -> cbRol.addItem(item)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistroEmpleado = new javax.swing.JPanel();
        lblRegistroEmpleado = new javax.swing.JLabel();
        lbltipodocumento = new javax.swing.JLabel();
        cbTiposDocumento = new javax.swing.JComboBox();
        lblNumeroDocumento = new javax.swing.JLabel();
        txtCreacionNumeroDocumento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCreacionNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCreacionPrimerApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCreacionSegundoApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox();
        txtCreacionUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCreacionPass = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtCreacionConfirmPass = new javax.swing.JPasswordField();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRegistroEmpleado.setName(""); // NOI18N

        lblRegistroEmpleado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblRegistroEmpleado.setText("Registrar Empleado");

        lbltipodocumento.setText("Tipo documento");

        lblNumeroDocumento.setText("Número documento");

        jLabel1.setText("Nombres");

        jLabel2.setText("Primer Apellido");

        jLabel3.setText("Segundo Apellido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Datos Personales");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Daos de usuario");

        jLabel6.setText("Rol");

        jLabel7.setText("Nombre de usuario");

        jLabel8.setText("Contraseña");

        jLabel9.setText("Confirmar contraseña");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroEmpleadoLayout = new javax.swing.GroupLayout(panelRegistroEmpleado);
        panelRegistroEmpleado.setLayout(panelRegistroEmpleadoLayout);
        panelRegistroEmpleadoLayout.setHorizontalGroup(
            panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(lblRegistroEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRegistroEmpleadoLayout.createSequentialGroup()
                            .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbTiposDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbltipodocumento))
                            .addGap(18, 18, 18)
                            .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNumeroDocumento)
                                .addComponent(txtCreacionNumeroDocumento)))
                        .addComponent(txtCreacionNombres)
                        .addGroup(panelRegistroEmpleadoLayout.createSequentialGroup()
                            .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txtCreacionPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCreacionSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addGroup(panelRegistroEmpleadoLayout.createSequentialGroup()
                            .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(txtCreacionUsername)))
                        .addGroup(panelRegistroEmpleadoLayout.createSequentialGroup()
                            .addComponent(txtCreacionPass, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtCreacionConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRegistroEmpleadoLayout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegistroEmpleadoLayout.setVerticalGroup(
            panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroEmpleadoLayout.createSequentialGroup()
                .addComponent(lblRegistroEmpleado)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipodocumento)
                    .addComponent(lblNumeroDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTiposDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreacionNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCreacionNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreacionPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreacionSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreacionUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreacionPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreacionConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistroEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistroEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            this.verificarDatos();
            Persona persona = new Persona();
            persona.setIdTipoDocumentoPersona((TipoDocumento) cbTiposDocumento.getSelectedItem());
            persona.setNumeroDocumentoPersona(txtCreacionNumeroDocumento.getText());
            persona.setNombresPersona(txtCreacionNombres.getText());
            persona.setPrimerApellidoPersona(txtCreacionPrimerApellido.getText());
            persona.setSegundoApellidoPersona(txtCreacionSegundoApellido.getText());
            Usuario usuario = new Usuario();
            usuario.setIdRolUsuario((Rol) cbRol.getSelectedItem());
            usuario.setNombreUsuario(txtCreacionUsername.getText());
            usuario.setPassUsuario(new String(txtCreacionPass.getPassword()));
            this.logica.crearUsuario(persona, usuario);
            //int input = JOptionPane.showOptionDialog(this, "Usuario creado de manera exitosa", "informacion", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
            JOptionPane.showMessageDialog(this, "Usuario creado de manera exitosa");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void verificarDatos() throws Exception {
        if (cbTiposDocumento.getSelectedIndex() != 0
                && !txtCreacionNumeroDocumento.getText().trim().isEmpty()
                && !txtCreacionNombres.getText().trim().isEmpty()
                && txtCreacionPass.getPassword().length != 0
                && txtCreacionConfirmPass.getPassword().length != 0
                && cbRol.getSelectedIndex() != 0
                && !txtCreacionUsername.getText().trim().isEmpty()) {
            String pass = new String(txtCreacionPass.getPassword());
            String confirm = new String(txtCreacionConfirmPass.getPassword());
            if (!pass.equals(confirm)) {
                throw new Exception("La verificación de contraseña no coincide");
            } else {
                if (!StringUtil.checkExpressionPass(pass)) {
                    throw new Exception(StringUtil.MESAJE_ERROR_PASS);
                }
            }
        } else {
            throw new Exception("Por favor diligencie todo el formulario");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox cbRol;
    private javax.swing.JComboBox cbTiposDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblNumeroDocumento;
    private javax.swing.JLabel lblRegistroEmpleado;
    private javax.swing.JLabel lbltipodocumento;
    private javax.swing.JPanel panelRegistroEmpleado;
    private javax.swing.JPasswordField txtCreacionConfirmPass;
    private javax.swing.JTextField txtCreacionNombres;
    private javax.swing.JTextField txtCreacionNumeroDocumento;
    private javax.swing.JPasswordField txtCreacionPass;
    private javax.swing.JTextField txtCreacionPrimerApellido;
    private javax.swing.JTextField txtCreacionSegundoApellido;
    private javax.swing.JTextField txtCreacionUsername;
    // End of variables declaration//GEN-END:variables
}
