/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appempresaseguridad.gui.secretaria;

import appempresaseguridad.logic.secretaria.SecretariaLogica;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Felipe Garcia
 */
public class SecretariaFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    public SecretariaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmpleados = new javax.swing.JMenu();
        jOptionConsultar = new javax.swing.JMenuItem();
        jOptionActualizar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenida Secretaria");
        setAlwaysOnTop(true);

        menuEmpleados.setText("Empleados");

        jOptionConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jOptionConsultar.setText("Registrar");
        jOptionConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOptionConsultarActionPerformed(evt);
            }
        });
        menuEmpleados.add(jOptionConsultar);

        jOptionActualizar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jOptionActualizar.setText("Actualizar");
        jOptionActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOptionActualizarActionPerformed(evt);
            }
        });
        menuEmpleados.add(jOptionActualizar);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem1.setText("Consultar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuEmpleados.add(jMenuItem1);

        jMenuBar1.add(menuEmpleados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOptionConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOptionConsultarActionPerformed
        CreacionEmpleadoDialog creacionFrame = new CreacionEmpleadoDialog(this, rootPaneCheckingEnabled);
        creacionFrame.setLocationRelativeTo(null);
        creacionFrame.setVisible(true);
    }//GEN-LAST:event_jOptionConsultarActionPerformed

    private void jOptionActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOptionActualizarActionPerformed
        ActualizacionEmpleadoDialog actDialog = new ActualizacionEmpleadoDialog(this, rootPaneCheckingEnabled);
        actDialog.setLocationRelativeTo(null);
        actDialog.setVisible(true);
    }//GEN-LAST:event_jOptionActualizarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ConsultaEmpleadosDialog consDialog = new ConsultaEmpleadosDialog(this, rootPaneCheckingEnabled);
        consDialog.setLocationRelativeTo(null);
        consDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jOptionActualizar;
    private javax.swing.JMenuItem jOptionConsultar;
    private javax.swing.JMenu menuEmpleados;
    // End of variables declaration//GEN-END:variables

    //Propiedades propias
    SecretariaLogica logica;
}
